services:
  - type: pyservice
    name: pos-api
    runtime: python-3.12
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    workingDirectory: app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
    plan: free

  - type: pserv
    name: pos-db
    plan: free
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres
      - key: POSTGRES_DB
        value: pos-db
