services:
  - type: pserv
    name: pos-db
    env: docker       
    plan: free
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres
      - key: POSTGRES_DB
        value: pos-db

  - type: web
    name: pos-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgres://postgres:postgres@pos-db:5432/pos-db
